version: "3.8"

services:
  # Mysql
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    healthcheck:
      test: mysql -u root -p$${MYSQL_ROOT_PASSWORD} -h 127.0.0.1 -e 'SHOW DATABASES;'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # JDK 21 + Alpine
  backend:
    image: zapss/discharge-jdk:latest
    container_name: java_container
    environment:
      # Acesso ao Container DB
      DB_URL: jdbc:mysql://db/${MYSQL_DATABASE}
      DB_USER: ${BACKEND_DB_USER}
      DB_PASSWORD: ${BACKEND_DB_PASSWORD}
      # Acesso ao S3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      TOKEN: ${TOKEN}
    ports:
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy

  # Node.js + Alpine
  frontend:
    image: zapss/discharge-nodejs:latest
    container_name: node_container
    environment:
      AMBIENTE_PROCESSO: ${AMBIENTE_PROCESSO}
      DB_HOST: ${FRONTEND_DB_HOST}
      DB_DATABASE: ${FRONTEND_DB_DATABASE}
      DB_USER: ${FRONTEND_DB_USER}
      DB_PASSWORD: ${FRONTEND_DB_PASSWORD}
      DB_PORT: ${FRONTEND_DB_PORT}
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
      MEU_EMAIL: ${MEU_EMAIL}
      MINHA_SENHA: ${MINHA_SENHA}
    restart: always
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
